services:
  - type: web
    name: django-face-login
    env: docker
    plan: free
    region: oregon
    branch: main  # Change if your branch is different
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DJANGO_SECRET_KEY
        value: )5uiel=zqh0s2658msi7=i6p!*lp7btx*=l5cwsj9pjihaa&$@  # Replace with a real secret key
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "django-face-login.onrender.com"  # Your Render domain
      - key: DJANGO_SETTINGS_MODULE
        value: face_login_project.settings  # Replace with your actual settings path
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"

databases:
  - name: django-db
    plan: free
    region: oregon
