services:
  - type: web
    name: django-face-login
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn face_login_project.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: your-production-secret-key
      - key: DATABASE_URL
        fromDatabase:
          name: face-login-db
          property: connectionString

databases:
  - name: face-login-db
    plan: free
