services:
  - type: web
    name: django-face-login
    env: docker
    plan: free
    region: oregon
    branch: main  # or your branch name
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your_secret_key_here
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "your-app-name.onrender.com"
    buildCommand: ""
    startCommand: ""

databases:
  - name: django-db
    plan: free
    region: oregon
